<Project>
  <PropertyGroup>
    <!-- Enable central package management, https://learn.microsoft.com/en-us/nuget/consume-packages/Central-Package-Management -->
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="AspNetCore.SassCompiler" Version="1.99.0" />
    <PackageVersion Include="CommandLineParser" Version="2.9.1" />
    <PackageVersion Include="dnlib" Version="4.5.0" />
    <PackageVersion Include="Microsoft.AspNetCore.Components.Web" Version="10.0.10" />
    <PackageVersion Include="Microsoft.AspNetCore.Components.WebView.Maui" Version="10.0.51" />
    <PackageVersion Include="Microsoft.AspNetCore.SignalR.Client" Version="10.0.8" />
    <PackageVersion Include="Microsoft.Maui.Controls" Version="10.0.51" />
    <PackageVersion Include="Microsoft.Maui.Controls.Compatibility" Version="10.0.51" />
    <PackageVersion Include="MudBlazor" Version="9.7.0" />
    <PackageVersion Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageVersion Include="OneOf" Version="3.0.271" />
    <PackageVersion Include="OpenShock.MinimalEvents" Version="0.0.1" />
    <PackageVersion Include="OpenShock.SDK.CSharp" Version="0.0.40" />
    <PackageVersion Include="OpenShock.SDK.CSharp.Hub" Version="0.0.40" />
    <PackageVersion Include="OpenShock.SDK.CSharp.Live" Version="0.0.40" />
    <PackageVersion Include="Photino.Blazor" Version="4.0.13" />
    <PackageVersion Include="Semver" Version="3.0.0" />
    <PackageVersion Include="Serilog" Version="4.3.1" />
    <PackageVersion Include="Serilog.Extensions.Hosting" Version="10.0.0" />
    <PackageVersion Include="Serilog.Extensions.Logging" Version="10.0.0" />
    <PackageVersion Include="Serilog.Sinks.Console" Version="6.1.1" />
    <PackageVersion Include="Serilog.Sinks.Debug" Version="3.0.0" />
    <PackageVersion Include="Serilog.Sinks.File" Version="7.0.0" />
    <PackageVersion Include="System.Reactive" Version="6.1.0" />
    <PackageVersion Include="System.IO.Ports" Version="10.0.10" />
    <PackageVersion Include="TUnit" Version="1.63.0" />
  </ItemGroup>
</Project>