<Project Sdk="Microsoft.NET.Sdk.Razor">

    <!-- Import module packaging targets (provided automatically via NuGet, manual import needed for ProjectReference) -->
    <Import Project="../ModuleBase/build/OpenShock.Desktop.ModuleBase.props" />

    <PropertyGroup>
        <OpenShockModuleId>openshock.desktop.modules.examplemodule</OpenShockModuleId>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <OutputType>Library</OutputType>
        <AssemblyName>OpenShock.Desktop.Modules.ExampleModule</AssemblyName>
        <RootNamespace>OpenShock.Desktop.Modules.ExampleModule</RootNamespace>
        <Configurations>Debug;Release</Configurations>
        <Platforms>AnyCPU</Platforms>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\ModuleBase\ModuleBase.csproj" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="Icon.svg" />
      <EmbeddedResource Include="Icon.svg" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="MudBlazor" Version="9.1.0" />
      <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    </ItemGroup>

    <!-- Import module packaging targets (provided automatically via NuGet, manual import needed for ProjectReference) -->
    <Import Project="../ModuleBase/build/OpenShock.Desktop.ModuleBase.targets" />

</Project>
