on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
    types: [opened, reopened, synchronize]
  workflow_call:
  workflow_dispatch:

name: build-module-base

env:
  DOTNET_VERSION: 9.0.x
  REGISTRY: ghcr.io

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET SDK ${{ env.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Cache NuGet packages
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: module-base-nuget
          restore-keys: |
            module-base-nuget-

      - name: Publish OpenShock Desktop Module Base
        run: dotnet publish ModuleBase/ModuleBase.csproj -c Release-Windows -o ./publish/ModuleBase

      - name: Upload OpenShock Desktop Module Base artifacts
        uses: actions/upload-artifact@v4
        with:
          name: OpenShock Desktop Module Base
          path: |
            ./publish/ModuleBase/*.nupkg
            ./publish/ModuleBase/*.snupkg
          retention-days: 1
          if-no-files-found: error