on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
    types: [opened, reopened, synchronize]
  workflow_call:
  workflow_dispatch:

name: ci-build

env:
  DOTNET_VERSION: 9.0.x
  REGISTRY: ghcr.io

jobs:

  build-windows-maui:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET SDK ${{ env.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          
      - name: Install maui workload for windows
        run: dotnet workload install maui-windows

      - name: Cache NuGet packages
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: windows-maui-nuget
          restore-keys: |
            windows-maui-nuget

      - name: Publish OpenShock Desktop Windows
        run: dotnet publish Desktop/Desktop.csproj -c Release-Windows -o ./publish/Windows-Maui

      - name: Upload OpenShock Desktop Windows artifacts
        uses: actions/upload-artifact@v4
        with:
          name: OpenShock Desktop Windows MAUI
          path: publish/Windows-Maui/*
          retention-days: 1
          if-no-files-found: error
  
  installer-windows-maui:
    runs-on: windows-latest
    needs: build-windows-maui

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            Installer

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: OpenShock Desktop Windows MAUI
          path: publish/


      - name: Create nsis installer
        uses: joncloud/makensis-action@publish
        with:
          script-file: ${{ github.workspace }}/Installer/installer.nsi
          additional-plugin-paths: ${{ github.workspace }}/Installer/Plugins
          
      - name: Upload OpenShock Desktop Windows Setup
        uses: actions/upload-artifact@v4
        with:
          name: OpenShock_Desktop_Setup
          path: Installer/OpenShock_Desktop_Setup.exe
          retention-days: 7
          if-no-files-found: error


  build-linux-web:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET SDK ${{ env.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Cache NuGet packages
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: linux-web-nuget
          restore-keys: |
            linux-web-nuget

      - name: Publish OpenShock Web
        run: dotnet publish Desktop/Desktop.csproj -c Release-Web -o ./publish/Web-Linux