on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+-rc.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+-preview.[0-9]+'

name: ci-tag

jobs:

  # Pre-job to find the latest tag
  get-latest-tag:
    runs-on: ubuntu-latest
    outputs:
      latest-tag: ${{ steps.latest-tag.outputs.tag }}
    steps:
      - name: Find latest tag
        id: latest-tag
        uses: oprypin/find-latest-tag@v1
        with:
          repository: ${{ github.repository }}
          regex: '^\d+\.\d+\.\d+(-[0-9A-Za-z]+(\.\d+)*)?$'
          releases-only: false
      - name: Set output
        run: echo "latest-tag=${{ steps.latest-tag.outputs.tag }}"

  # Delegate building and containerizing to a single workflow.
  build:
    needs: get-latest-tag
    uses: ./.github/workflows/ci-build.yml
    with:
      platforms: linux/amd64,linux/arm64
      latest: ${{ needs.get-latest-tag.outputs.latest-tag == github.ref_name }}