<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <SingleProject>true</SingleProject>
        <EnableDefaultCssItems>false</EnableDefaultCssItems>
        <ApplicationTitle>OpenShock</ApplicationTitle>

        <AssemblyName>OpenShock.Desktop</AssemblyName>
        <RootNamespace>OpenShock.Desktop</RootNamespace>
        
        <ApplicationIcon>wwwroot/images/openshock-icon.ico</ApplicationIcon>
        <SelfContained>true</SelfContained>

        <PackageIcon>wwwroot/images/Icon512.png</PackageIcon>

        <ResourceLanguages>en</ResourceLanguages>
        <SatelliteResourceLanguages>en-US;en</SatelliteResourceLanguages>
        <IsPackable>false</IsPackable>

        <DefineConstants>DISABLE_XAML_GENERATED_MAIN</DefineConstants>

        <Configurations>Release-Windows;Debug-Windows;Release-Photino;Debug-Photino;Release-Web;Debug-Web</Configurations>

        <SupportedOSPlatformVersion>10.0.17763.0</SupportedOSPlatformVersion>
        <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)' == 'Debug-Windows' Or '$(Configuration)' == 'Release-Windows'">
        <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
        <WindowsPackageType>None</WindowsPackageType>
        <UseMaui>true</UseMaui>
        <DefineConstants>MAUI</DefineConstants>
        <StartupObject>OpenShock.Desktop.Platforms.Windows.WindowsEntryPoint</StartupObject>
        <SkipValidateMauiImplicitPackageReferences>true</SkipValidateMauiImplicitPackageReferences>
    </PropertyGroup>

    <ItemGroup Condition="'$(Configuration)' == 'Debug-Windows' Or '$(Configuration)' == 'Release-Windows'">
        <PackageReference Include="Microsoft.Maui.Controls" />
        <PackageReference Include="Microsoft.Maui.Controls.Compatibility" />
        <PackageReference Include="Microsoft.AspNetCore.Components.WebView.Maui" />
    </ItemGroup>

    <PropertyGroup Condition="'$(Configuration)' == 'Debug-Photino' Or '$(Configuration)' == 'Release-Photino'">
        <TargetFramework>net10.0</TargetFramework>
        <StartupObject>OpenShock.Desktop.Platforms.Photino.PhotinoEntryPoint</StartupObject>
        <DefineConstants>PHOTINO</DefineConstants>
        <RuntimeIdentifier>linux-x64</RuntimeIdentifier>
    </PropertyGroup>

    <ItemGroup Condition="'$(Configuration)' == 'Debug-Photino' Or '$(Configuration)' == 'Release-Photino'">
        <PackageReference Include="Photino.Blazor" />
    </ItemGroup>

    <PropertyGroup Condition="'$(Configuration)' == 'Debug-Web' Or '$(Configuration)' == 'Release-Web' ">
        <TargetFramework>net10.0</TargetFramework>
        <StartupObject>OpenShock.Desktop.Platforms.Web.WebEntryPoint</StartupObject>
        <DefineConstants>WEB</DefineConstants>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="AspNetCore.SassCompiler" />
        <PackageReference Include="CommandLineParser" />
        <PackageReference Include="dnlib" />
        <PackageReference Include="MudBlazor" />
        <PackageReference Include="OneOf" />
        <PackageReference Include="Semver" />
        <PackageReference Include="Serilog" />
        <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" />
        <PackageReference Include="Serilog.Extensions.Hosting" />
        <PackageReference Include="Serilog.Extensions.Logging" />
        <PackageReference Include="Serilog.Sinks.Console" />
        <PackageReference Include="Serilog.Sinks.Debug" />
        <PackageReference Include="OpenShock.SDK.CSharp" />
        <PackageReference Include="OpenShock.SDK.CSharp.Hub" />
        <PackageReference Include="OpenShock.SDK.CSharp.Live" />
        <PackageReference Include="Serilog.Sinks.File" />
        <PackageReference Include="System.Reactive" />
    </ItemGroup>

    <ItemGroup>
        <Content Update="wwwroot\**">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\ModuleBase\ModuleBase.csproj" />
    </ItemGroup>

    <ItemGroup>
      <_ContentIncludedByDefault Remove="wwwroot\deps\MudBlazor\MudBlazor.min.css" />
      <_ContentIncludedByDefault Remove="wwwroot\deps\MudBlazor\MudBlazor.min.js" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="wwwroot\css\" />
    </ItemGroup>

    <PropertyGroup>
        <ServerGarbageCollection>false</ServerGarbageCollection>
    </PropertyGroup>

</Project>
